query user($_id: String!) {
    user(_id: $_id) {
        _id
        firstName
        lastName
        roles
        email
    }
}
query users{
    users {
        _id
        firstName
        lastName
        roles
        email
        createdAt
        lastLogin
    }
}
query currentUser {
    currentUser {
        _id
        firstName
        lastName
        roles
        email
    }
}
