export default {
    ADD_ACTIVE_ACTION: 'ADD_ACTIVE_ACTION',
    REMOVE_ACTIVE_ACTION: 'REMOVE_ACTIVE_ACTION',
    UPDATE_ACTIVE_ACTION: 'UPDATE_ACTIVE_ACTION',
    ADD_RESPONSE_ERROR: 'ADD_RESPONSE_ERROR',
    REMOVE_RESPONSE_ERROR: 'REMOVE_RESPONSE_ERROR',
    UPDATE_RESPONSE_ERROR: 'UPDATE_RESPONSE_ERROR',
    SET_NETWORK_ERRORS: 'SET_NETWORK_ERRORS',
};
